version: '3'
services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  flyway:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
